### ISSUE TITLE
Error Microsoft.Data.Sqlite

### ISSUE THREAD

**Issue by KiLoS102** [anegostudios/VintagestoryServerArm64#4]
Hello, i have error in terminal on Linux, all versions below 1.19.0 working very well.
Hardware is RPi4B+ 8GB
Linux raspberrypi 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

```javascript
pi@raspberrypi:~/Servers/VintageStory/vintagestory-v1.19.3 $ dotnet VintagestoryServer.dll 
28.1.2024 18:49:00 [Server Notification] Server logger started.
28.1.2024 18:49:00 [Server Notification] Game Version: v1.19.3 (Stable)
28.1.2024 18:49:01 [Server Notification] C# Framework: .net 7.0.15
28.1.2024 18:49:01 [Server Notification] Zstd Version: 1.5.4
28.1.2024 18:49:01 [Server Notification] Operating System: Linux (Debian GNU/Linux 12 (bookworm)) [Kernel 6.1.0.7]
28.1.2024 18:49:02 [Server Event] Launching server...
28.1.2024 18:49:02 [Server Event] Server v1.19.3, network v1.19.5, api v1.19.0
28.1.2024 18:49:02 [Server Notification] Entering runphase Initialization
28.1.2024 18:49:02 [Server Event] Loading configuration...
28.1.2024 18:49:02 [Server Notification] Entering runphase Configuration
28.1.2024 18:49:02 [Server Fatal] Unable to open or create savegame.
28.1.2024 18:49:02 [Server Error] Exception: Could not load file or assembly 'Microsoft.Data.Sqlite, Version=7.0.14.0, Culture=neutral, PublicKeyToken=adb9793xxxddae60'. The system cannot find the file specified.

   at Vintagestory.Common.GameDatabase.OpenConnection(String databaseFilename, Int32 databaseVersion, String& errorMessage, Boolean requireWriteAccess, Boolean corruptionProtection, Boolean doIntegrityCheck)
   at Vintagestory.Common.GameDatabase.ProbeOpenConnection(String databaseFilename, Boolean corruptionProtection, Int32& foundVersion, String& errorMessage, Boolean& isReadonly, Boolean requireWrite) in VintagestoryLib\Common\FileIO\Database\GameDatabase.cs:line 139
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnBeginConfiguration() in VintagestoryLib\Server\Systems\World\LoadThread\LoadSaveGame.cs:line 72
28.1.2024 18:49:02 [Server Notification] Server stop requested, begin shutdown sequence. Stop reason: Failed opening savegame
28.1.2024 18:49:02 [Server Notification] Entering runphase Shutdown
28.1.2024 18:49:02 [Server Event] Shutting down 4 server threads... 
28.1.2024 18:49:02 [Server Event] Killed console thread
28.1.2024 18:49:03 [Server Event] All threads gracefully shut down
28.1.2024 18:49:03 [Server Event] Doing last tick...
28.1.2024 18:49:03 [Server Event] Stopped the server!
``` 
Thank you for help.

**Comment by Th3Dilli** [comment]
This is since we changed in 1.19 to use Microsoft.Data.Sqlite instead of System.Data.Sqlite to make amr64 releases easier in the future.

So you are likely using the wrong Libs from an previous 1.18 .tar.gz, see the [release](https://github.com/anegostudios/VintagestoryServerArm64/releases) page and get the new 1.19 tar.gz and merge that with the latest (1.19.3 as of now)  from our official site

**Comment by Th3Dilli** [comment]
closing since i think their is not more to be done here
